// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAukz5Bl3gTrUwtMjdaIcN2PVAC_sxzqNU',
    appId: '1:294100117441:web:9e3dc43a0a5ebd82b8f140',
    messagingSenderId: '294100117441',
    projectId: 'chat-689b6',
    authDomain: 'chat-689b6.firebaseapp.com',
    storageBucket: 'chat-689b6.firebasestorage.app',
    measurementId: 'G-4K2QYH38H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKI84B1tq5qjy2Rd0B-rb3lrxHuFcA_2k',
    appId: '1:294100117441:android:9b933b19f594c4b1b8f140',
    messagingSenderId: '294100117441',
    projectId: 'chat-689b6',
    storageBucket: 'chat-689b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuL5ynQWOQUsGHe_R6plKSA2V2I19Peyk',
    appId: '1:294100117441:ios:5ec05a2ba325e069b8f140',
    messagingSenderId: '294100117441',
    projectId: 'chat-689b6',
    storageBucket: 'chat-689b6.firebasestorage.app',
    iosBundleId: 'com.example.aiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuL5ynQWOQUsGHe_R6plKSA2V2I19Peyk',
    appId: '1:294100117441:ios:5ec05a2ba325e069b8f140',
    messagingSenderId: '294100117441',
    projectId: 'chat-689b6',
    storageBucket: 'chat-689b6.firebasestorage.app',
    iosBundleId: 'com.example.aiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAukz5Bl3gTrUwtMjdaIcN2PVAC_sxzqNU',
    appId: '1:294100117441:web:0b0e1ff3558e9126b8f140',
    messagingSenderId: '294100117441',
    projectId: 'chat-689b6',
    authDomain: 'chat-689b6.firebaseapp.com',
    storageBucket: 'chat-689b6.firebasestorage.app',
    measurementId: 'G-GJ9HYKGN6Z',
  );
}
